// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSsH5UNxh2LThrGhG1tEB94gyptJCRTPw',
    appId: '1:113541485341:web:d28a725ab869f324b9c7f4',
    messagingSenderId: '113541485341',
    projectId: 'ticket-d44a2',
    authDomain: 'ticket-d44a2.firebaseapp.com',
    storageBucket: 'ticket-d44a2.appspot.com',
    measurementId: 'G-S63BENZQCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAezo2Pvupj0U9b1BE2q79RH3K0qEfGeGc',
    appId: '1:113541485341:android:4b020039b62efe2bb9c7f4',
    messagingSenderId: '113541485341',
    projectId: 'ticket-d44a2',
    storageBucket: 'ticket-d44a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAql3JDVialbKH6cLBfph8qfMCfF-kRceo',
    appId: '1:113541485341:ios:4fd07914a6d53082b9c7f4',
    messagingSenderId: '113541485341',
    projectId: 'ticket-d44a2',
    storageBucket: 'ticket-d44a2.appspot.com',
    iosBundleId: 'com.ticket.ticketsysytem',
  );
}
